defaults: &defaults
  working_directory: /go/src/github.com/jun06t/sample-api
  environment:
    TZ: "/usr/share/zoneinfo/Asia/Tokyo"

version: 2
jobs:
  test:
    <<: *defaults
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - restore_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
      - run:
          name: Setup For Test
          command: |
            if [ ! -e vendor ]; then
              dep ensure
            fi
      - run:
          name: Run Tests
          command: |
            make test
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor

  deploy_dev:
    <<: *defaults
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - restore_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            make build
      - deploy:
          name: Deploy container
          command: |
            ./scripts/deploy.sh dev latest

  deploy_stg:
    <<: *defaults
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - restore_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            make build
      - deploy:
          name: Deploy container
          command: |
            ./scripts/deploy.sh stg ${CIRCLE_TAG}


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy_stg:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9](\.[0-9]){2}$/