version: 2.1
#defaults: &defaults
#      docker:
#        #- image: circleci/node:14
#        - image: circleci/node:16.9.0
#      working_directory: ~/app
orbs:
  aws-cli: circleci/aws-cli@1.3.2
jobs:
  build:   
    docker:
        - image: circleci/node:16.9.0
    working_directory: ~/app
    steps:     
      #- run: yarn test
      - run: ls -la
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
        filters:
          tags:
            only: /^deploy_(develop|product)_(A|B)$/
          branches:
            ignore: /.*/