version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.2
jobs:
  deploy_stg:
    working_directory: /go/src/github.com/jun06t/sample-api
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
    docker:
      - image: circleci/node:16.9.0
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            ls -la



workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deploy_stg:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /foo.+/