defaults: &defaults
  working_directory: /go/src/github.com/jun06t/sample-api
  environment:
    TZ: "/usr/share/zoneinfo/Asia/Tokyo"

version: 2.1
jobs:
  deploy_stg:
    <<: *defaults
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            ls -la



workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - deploy_stg:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /foo.+/